### ISSUE TITLE
Sidebar menu not functioning on Mobile Screen in "Hogfather" RC3

### ISSUE THREAD

**Issue by 0936159951** [IceWreck/Argon-Dokuwiki-Template#31]
Look great on Pad, but collapsible menu not working for sidebar on small mobile screen.

**Comment by SoarinFerret** [comment]
After initially looking at this, I see a couple of issues:

- DokuWiki now has a new feature to [defer all JS](https://www.dokuwiki.org/config:defer_js) to improve performance, however, at the expense of some plugins/templates no longer working. You can disable it at the following URL: `/doku.php?id=start&do=admin&page=config#_feature_flags` - this fixes the button no longer working until the theme gets updated to also work with deferred JS.
- DokuWiki has updated from jQuery 3.1.1 to jQuery 3.5.0, which is having some issues with the bootstrap. You can see the issue thread [here](https://github.com/twbs/bootstrap/issues/30553). The fix for this is upgrading bootstrap to v4.5.0

However, this is not an ideal fix - bootstrap v4.5.0 says it requires jQuery 3.5.1, not the 3.5.0 the latest Hogfather release candidate (2020-06-09) is including. I created a [pull request against DokuWiki](https://github.com/splitbrain/dokuwiki/pull/3192) to address this.

While I do not see any major issues using bootstrap 4.5.0 with Hogfather on jquery 3.5.0, that's not to say there are none.

@IceWreck What are your thoughts on this?

**Comment by IceWreck** [comment]
Thanks!
I'd say lets just upgrade to Bootstrap v4.5 here.

[This](https://github.com/twbs/bootstrap/pull/30559) patch, included in Bootstrap 4.5 was made to fix the issues caused by upgrading jQuery to 3.5.0 and [the navbar works](https://deploy-preview-30559--twbs-bootstrap.netlify.app/docs/4.4/examples/sticky-footer-navbar/) This should hopefully work until dokuwiki switches to 3.5.1

I'll work on making this theme work with Hogfather tonight (unless you've already started and in that case tell me)

**Comment by IceWreck** [comment]
I vaguely remember seeking this before in the dokuwiki docs
`Note that $() is not (and never was) the jQuery shortcut, jQuery is only available in it's long form of jQuery().`

pretty sure i did something about it to get bootstrap js to run but dont remember what

.Edit: this has nothing to do with anything here

**Comment by SoarinFerret** [comment]
@IceWreck Looks like my pull request to dokuwiki was merged, so when hogfather officially comes out we will have the 3.5.1 properly supported. Also, I installed your latest commits just now, looks like everything is working properly, including the deferred JS - thank you very much!!

@0936159951 I believe these latest changes fix this - can this be closed?

**Comment by 0936159951** [comment]
Thanks
